train_folder : "Data/train_data"
dev_folder : "Data/dev_data"

batch_size : 32
epochs : 7

image_size : 256
crop_size : 240

dropout_prob : 0.6
num_frozen_layers : 14 

learning_rate : 0.001
weight_decay : 0.0001
