*Instrucciones básicas*
1. Tome una pieza de madera.
2. Corte la madera con un bisturí en dirección perpendicular al crecimiento del árbol.
3. Rocíe la superficie expuesta con agua.
4. Capture una fotografía de la superficie con la lupa digital.
5. Envíe la fotografía como mensaje.

Se responderá con tres imágenes correspondientes a las especies más similares.

*Técnica de corte*
La hoja del bisturí solo debe pasar una vez por la superficie de la madera, con un movimiento uniforme. Para una explicación detallada de como realizar un buen corte puede consultar: https://www.fpl.fs.fed.us/documnts/pdf2011/fpl_2011_wiedenhoeft004.pdf

*Dirección de corte*
La madera debe ser cortada a través del grano, es decir en la misma dirección que se tala el árbol. Si desea conocer más acerca de la estructura de la madera puede consultar: https://www.fpl.fs.fed.us/documnts/pdf2011/fpl_2011_wiedenhoeft002.pdf


